security.jwt.secret=bWktY2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWp3dC0xMjM0NTY3ODkwMTIzNDU2
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-expiration=604800000
logging.file.name=logs/identity.log
logging.level.root=INFO
logging.level.edu.eci.dosw.service=INFO

app.seed.admin.email=admin@escuelaing.edu.co
app.seed.admin.password=Admin123*

app.seed.admin.name=Admin
app.seed.admin.last-name=System
app.seed.admin.birth-date=2000-01-01
app.seed.admin.relation=ESTUDIANTE
app.seed.admin.semester=1
app.seed.admin.program=SISTEMAS
app.seed.admin.gender=MALE
app.seed.admin.identification-type=CC
app.seed.admin.identification=ADMIN00001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
