security.jwt.secret=bWktY2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWp3dC0xMjM0NTY3ODkwMTIzNDU2
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-expiration=604800000
logging.file.name=logs/identity.log
logging.level.root=INFO
logging.level.edu.eci.dosw.service=INFO
app.seed.admin.email=admin@escuelaing.edu.co
app.seed.admin.password=Admin