spring.datasource.url=${AZURE_DB_URL}
spring.datasource.username=${AZURE_DB_USERNAME}
spring.datasource.password=${AZURE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
app.seed.admin.email=${ADMIN_EMAIL}
app.seed.admin.password=${ADMIN_PASSWORD}