security.jwt.secret=bWktY2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWp3dC0xMjM0NTY3ODkwMTIzNDU2
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-expiration=604800000
logging.file.name=logs/identity.log
logging.level.root=INFO
logging.level.edu.eci.dosw.service=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/TechCup-test
spring.datasource.username=test
spring.datasource.password=0TEST0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect