package edu.eci.dosw.dto;

public enum Program {
    INTELIGENCIA_ARTIFICIAL,
    CIBERSEGURIDAD,
    ESTADISTICA,
    SISTEMAS,
    BIOTECNOLOGIA,
    CIVIL,
    AMBIENTAL,
    ELECTRICA,
    INDUSTRIAL,
    ELECTRONICA,
    MECANICA,
    BIOMEDICA,
    ECONOMIA,
    ADMINISTRACION_EMPRESAS,
    MATEMATICAS
}